//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luma.SimpleEntity.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luma.SimpleEntity.Server.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; of entity type &apos;{1}&apos; cannot be marked with AssociationAttribute because &apos;{2}&apos; is not a valid entity type..
        /// </summary>
        public static string Association_Not_Entity_Type {
            get {
                return ResourceManager.GetString("Association_Not_Entity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to operation &apos;{0}&apos; was denied..
        /// </summary>
        public static string AuthorizationAttribute_Default_Message {
            get {
                return ResourceManager.GetString("AuthorizationAttribute_Default_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; AuthorizationAttribute must specify a non-empty &apos;ErrorMessage&apos; to access &apos;{1}&apos; resource type..
        /// </summary>
        public static string AuthorizationAttribute_Requires_ErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizationAttribute_Requires_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &apos;{0}&apos; does not expose a static string property named &apos;{1}&apos;..
        /// </summary>
        public static string AuthorizationAttribute_Requires_Valid_Property {
            get {
                return ResourceManager.GetString("AuthorizationAttribute_Requires_Valid_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AuthorizationContext instance is only a template and cannot be used directly.&quot;.
        /// </summary>
        public static string AuthorizationContext_Template_Only {
            get {
                return ResourceManager.GetString("AuthorizationContext_Template_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity does not exist in the ChangeSet..
        /// </summary>
        public static string ChangeSet_ChangeSetEntryNotFound {
            get {
                return ResourceManager.GetString("ChangeSet_ChangeSetEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ChangeSet : Entity for operation &apos;{0}&apos; has multiple parents..
        /// </summary>
        public static string ChangeSet_ChildHasMultipleParents {
            get {
                return ResourceManager.GetString("ChangeSet_ChildHasMultipleParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member expression specified is invalid..
        /// </summary>
        public static string ChangeSet_InvalidMemberExpression {
            get {
                return ResourceManager.GetString("ChangeSet_InvalidMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOriginal cannot be called for a new entity being inserted..
        /// </summary>
        public static string ChangeSet_OriginalNotValidForInsert {
            get {
                return ResourceManager.GetString("ChangeSet_OriginalNotValidForInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace entity of type &apos;{0}&apos; with entity of type &apos;{1}&apos;..
        /// </summary>
        public static string ChangeSet_Replace_EntityTypesNotSame {
            get {
                return ResourceManager.GetString("ChangeSet_Replace_EntityTypesNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed type &apos;{0}&apos; can only have a Delete method if all of its parent types also support Update or Delete..
        /// </summary>
        public static string Composition_ParentsMustSupportDelete {
            get {
                return ResourceManager.GetString("Composition_ParentsMustSupportDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed type &apos;{0}&apos; can only have an Insert method if all of its parent types also support Update or Insert..
        /// </summary>
        public static string Composition_ParentsMustSupportInsert {
            get {
                return ResourceManager.GetString("Composition_ParentsMustSupportInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed type &apos;{0}&apos; can only have an Update method if all of its parent types also support Update..
        /// </summary>
        public static string Composition_ParentsMustSupportUpdate {
            get {
                return ResourceManager.GetString("Composition_ParentsMustSupportUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MetadataTypeAttribute on type &apos;{0}&apos; results in a cyclic metadata provider chain. Either remove the attribute or remove the cycle..
        /// </summary>
        public static string CyclicMetadataTypeAttributesFound {
            get {
                return ResourceManager.GetString("CyclicMetadataTypeAttributesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; of type &apos;{1}&apos; is marked with the KeyAttribute.  Derived entity classes cannot declare key properties..
        /// </summary>
        public static string DerivedEntityCannotHaveKey {
            get {
                return ResourceManager.GetString("DerivedEntityCannotHaveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain operation &apos;{0}&apos; declared on the entity &apos;{1}&apos; must also be declared on the root entity &apos;{2}&apos;..
        /// </summary>
        public static string DomainOperation_Required_On_Root {
            get {
                return ResourceManager.GetString("DomainOperation_Required_On_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        public static string DomainOperationEntry_ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("DomainOperationEntry_ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method named &apos;{0}&apos; is already defined. DomainOperationEntry overloads are not supported..
        /// </summary>
        public static string DomainOperationEntryOverload_NotSupported {
            get {
                return ResourceManager.GetString("DomainOperationEntryOverload_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DomainService has been initialized for an operation of type &apos;{0}&apos; so it cannot be used for an operation of type &apos;{1}&apos;..
        /// </summary>
        public static string DomainService_InvalidOperationType {
            get {
                return ResourceManager.GetString("DomainService_InvalidOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid DomainService type. DomainService types cannot be abstract or generic..
        /// </summary>
        public static string DomainService_InvalidType {
            get {
                return ResourceManager.GetString("DomainService_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple invocations of entity action &apos;{0}.{1}&apos; is not allowed.
        /// </summary>
        public static string DomainService_MultipleEntityActionsNotAllowedFor {
            get {
                return ResourceManager.GetString("DomainService_MultipleEntityActionsNotAllowedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DomainService has not been initialized..
        /// </summary>
        public static string DomainService_NotInitialized {
            get {
                return ResourceManager.GetString("DomainService_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of type &apos;{0}&apos; already exists in the container..
        /// </summary>
        public static string DomainServiceContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("DomainServiceContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entity &apos;{0}&apos; in DomainService &apos;{1}&apos; does not have a key defined. Entity types exposed by DomainService operations must have at least one public property marked with the KeyAttribute..
        /// </summary>
        public static string Entity_Has_No_Key_Properties {
            get {
                return ResourceManager.GetString("Entity_Has_No_Key_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}.{1}&apos; is already defined by &apos;{2} and cannot be redefined..
        /// </summary>
        public static string Entity_Property_Redefined {
            get {
                return ResourceManager.GetString("Entity_Property_Redefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association &apos;{0}.{1}&apos; is marked with RequiredAttribute. Please remove the attribute and mark the underlying foreign key members with RequiredAttribute instead..
        /// </summary>
        public static string Entity_RequiredAssociationNotAllowed {
            get {
                return ResourceManager.GetString("Entity_RequiredAssociationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; must be marked with DataContractAttribute since it derives from type &apos;{1}&apos; which is marked with DataContractAttribute..
        /// </summary>
        public static string EntityDescription_DataContractAttributeRequired {
            get {
                return ResourceManager.GetString("EntityDescription_DataContractAttributeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query operation &apos;{0}&apos; cannot be marked as the default because it returns only a single value..
        /// </summary>
        public static string EntityDescription_DefaultQuery_Cannot_Be_Singleton {
            get {
                return ResourceManager.GetString("EntityDescription_DefaultQuery_Cannot_Be_Singleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both query operations &apos;{0}&apos; and &apos;{1}&apos; cannot be marked as the default query operation because they return the same entity type &apos;{2}&apos;..
        /// </summary>
        public static string EntityDescription_DefaultQuery_Cannot_Have_Multiple {
            get {
                return ResourceManager.GetString("EntityDescription_DefaultQuery_Cannot_Have_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both query operations &apos;{0}&apos; and &apos;{1}&apos; cannot be marked as the default query operation. Entity type &apos;{2}&apos; derives from entity type &apos;{3}&apos;.  The default query can expose only a single type for an entity hierarchy..
        /// </summary>
        public static string EntityDescription_DefaultQuery_Cannot_Have_Multiple_Inheritance {
            get {
                return ResourceManager.GetString("EntityDescription_DefaultQuery_Cannot_Have_Multiple_Inheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query operation &apos;{0}&apos; cannot be marked as the default because it declares parameters..
        /// </summary>
        public static string EntityDescription_DefaultQuery_Cannot_Have_Params {
            get {
                return ResourceManager.GetString("EntityDescription_DefaultQuery_Cannot_Have_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation &apos;{0}&apos; cannot be added to this DomainServiceDescription for type &apos;{1}&apos; because the operation&apos;s DomainServiceType is &apos;{2}&apos;..
        /// </summary>
        public static string EntityDescription_IncompatibleOperationParentType {
            get {
                return ResourceManager.GetString("EntityDescription_IncompatibleOperationParentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompositionAttribute cannot be applied to member &apos;{0}.{1}&apos;. CompositionAttribute can only be applied to members marked with AssociationAttribute..
        /// </summary>
        public static string EntityDescription_InvalidCompositionMember {
            get {
                return ResourceManager.GetString("EntityDescription_InvalidCompositionMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications cannot be made to a DomainServiceDescription once it has been initialized..
        /// </summary>
        public static string EntityDescription_InvalidUpdate {
            get {
                return ResourceManager.GetString("EntityDescription_InvalidUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; has more than one member marked with both TimestampAttribute and ConcurrencyCheckAttribute. An entity can have only one concurrency version member..
        /// </summary>
        public static string EntityDescription_MultipleVersionMembers {
            get {
                return ResourceManager.GetString("EntityDescription_MultipleVersionMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query operation &apos;{0}&apos; cannot be marked composable since its return type &apos;{1}&apos; does not implement IEnumerable of T..
        /// </summary>
        public static string EntityDescription_SingletonQueryMethodCannotCompose {
            get {
                return ResourceManager.GetString("EntityDescription_SingletonQueryMethodCannotCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DomainServiceDescription hasn&apos;t been initialized. Initialize must be called before the description can be used..
        /// </summary>
        public static string EntityDescription_Uninitialized {
            get {
                return ResourceManager.GetString("EntityDescription_Uninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainServiceDescriptionProvider type &apos;{0}&apos; must have a constructor with two parameters of types &apos;Type&apos; and &apos;DomainServiceDescriptionProvider&apos;, in that order..
        /// </summary>
        public static string EntityDescriptionProviderAttribute_MissingConstructor {
            get {
                return ResourceManager.GetString("EntityDescriptionProviderAttribute_MissingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity types cannot be a collection type..
        /// </summary>
        public static string EntityTypes_Cannot_Be_Collections {
            get {
                return ResourceManager.GetString("EntityTypes_Cannot_Be_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity types cannot be generic..
        /// </summary>
        public static string EntityTypes_Cannot_Be_Generic {
            get {
                return ResourceManager.GetString("EntityTypes_Cannot_Be_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity types cannot be nullable..
        /// </summary>
        public static string EntityTypes_Cannot_Be_Nullable {
            get {
                return ResourceManager.GetString("EntityTypes_Cannot_Be_Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity types cannot be a primitive type or a simple type like string or Guid..
        /// </summary>
        public static string EntityTypes_Cannot_Be_Primitives {
            get {
                return ResourceManager.GetString("EntityTypes_Cannot_Be_Primitives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity types must be public..
        /// </summary>
        public static string EntityTypes_Must_Be_Public {
            get {
                return ResourceManager.GetString("EntityTypes_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity types must have a default constructor..
        /// </summary>
        public static string EntityTypes_Must_Have_Default_Constructor {
            get {
                return ResourceManager.GetString("EntityTypes_Must_Have_Default_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter type &apos;{0}&apos; for parameter &apos;{1}&apos;. Expected type is &apos;{2}&apos;..
        /// </summary>
        public static string IncorrectParameterType {
            get {
                return ResourceManager.GetString("IncorrectParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &apos;{0}&apos; has a property &apos;{1}&apos; with an unsupported type..
        /// </summary>
        public static string Invalid_Entity_Property {
            get {
                return ResourceManager.GetString("Invalid_Entity_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a valid entity type.  {1}.
        /// </summary>
        public static string Invalid_Entity_Type {
            get {
                return ResourceManager.GetString("Invalid_Entity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}.{1}&apos; is an optimistic concurrency check member, but is either excluded or non-serializable..
        /// </summary>
        public static string Invalid_Exclude_Property_Concurency_Conflict {
            get {
                return ResourceManager.GetString("Invalid_Exclude_Property_Concurency_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; in entity type &apos;{1}&apos; cannot be marked with the IncludeAttribute because &apos;{2}&apos; is not a valid entity type.  {3}.
        /// </summary>
        public static string Invalid_Include_Invalid_Entity {
            get {
                return ResourceManager.GetString("Invalid_Include_Invalid_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid. It is a foreign key association but the property type is not a singleton..
        /// </summary>
        public static string InvalidAssociation_FKNotSingleton {
            get {
                return ResourceManager.GetString("InvalidAssociation_FKNotSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association named &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid: one and only one side of the association must have IsForeignKey set to true..
        /// </summary>
        public static string InvalidAssociation_IsFKInvalid {
            get {
                return ResourceManager.GetString("InvalidAssociation_IsFKInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association named &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid: the number of keys in &apos;{2}&apos; does not match the number in &apos;{3}&apos;..
        /// </summary>
        public static string InvalidAssociation_Key_Count_Mismatch {
            get {
                return ResourceManager.GetString("InvalidAssociation_Key_Count_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association defined on property &apos;{0}&apos; of entity &apos;{1}&apos; is invalid: Name cannot be null or empty..
        /// </summary>
        public static string InvalidAssociation_NameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("InvalidAssociation_NameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association name &apos;{0}&apos; defined on entity type &apos;{1}&apos; is not unique..
        /// </summary>
        public static string InvalidAssociation_NonUniqueAssociationName {
            get {
                return ResourceManager.GetString("InvalidAssociation_NonUniqueAssociationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association named &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid: OtherKey property named &apos;{2}&apos; cannot be found on entity type &apos;{3}&apos;..
        /// </summary>
        public static string InvalidAssociation_OtherKeyNotFound {
            get {
                return ResourceManager.GetString("InvalidAssociation_OtherKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association named &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid: Association members cannot be marked with RoundtripOriginalAttribute..
        /// </summary>
        public static string InvalidAssociation_RoundTripOriginal {
            get {
                return ResourceManager.GetString("InvalidAssociation_RoundTripOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association named &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid: {2} cannot be null or empty..
        /// </summary>
        public static string InvalidAssociation_StringCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("InvalidAssociation_StringCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association named &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid: ThisKey property named &apos;{2}&apos; cannot be found..
        /// </summary>
        public static string InvalidAssociation_ThisKeyNotFound {
            get {
                return ResourceManager.GetString("InvalidAssociation_ThisKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association &apos;{0}&apos; defined on entity type &apos;{1}&apos; is invalid. The corresponding association on &apos;{2}&apos; is not a valid back reference..
        /// </summary>
        public static string InvalidAssociation_TypesDoNotAlign {
            get {
                return ResourceManager.GetString("InvalidAssociation_TypesDoNotAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ChangeSet : {0}.
        /// </summary>
        public static string InvalidChangeSet {
            get {
                return ResourceManager.GetString("InvalidChangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id &apos;{0}&apos; specified for association member  &apos;{0}.{1}&apos; is invalid..
        /// </summary>
        public static string InvalidChangeSet_AssociatedIdNotInChangeset {
            get {
                return ResourceManager.GetString("InvalidChangeSet_AssociatedIdNotInChangeset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Ids for member &apos;{0}.{1}&apos; cannot be null..
        /// </summary>
        public static string InvalidChangeSet_AssociatedIdsCannotBeNull {
            get {
                return ResourceManager.GetString("InvalidChangeSet_AssociatedIdsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one entry for a given entity instance can exist in the ChangeSet..
        /// </summary>
        public static string InvalidChangeSet_DuplicateEntity {
            get {
                return ResourceManager.GetString("InvalidChangeSet_DuplicateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must be unique for each entry..
        /// </summary>
        public static string InvalidChangeSet_DuplicateId {
            get {
                return ResourceManager.GetString("InvalidChangeSet_DuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OriginalEntity cannot be specified for an Insert operation..
        /// </summary>
        public static string InvalidChangeSet_InsertsCantHaveOriginal {
            get {
                return ResourceManager.GetString("InvalidChangeSet_InsertsCantHaveOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association member &apos;{0}.{1}&apos; specified in the ChangeSet does not exist or is not marked with AssociationAttribute..
        /// </summary>
        public static string InvalidChangeSet_InvalidAssociationMember {
            get {
                return ResourceManager.GetString("InvalidChangeSet_InvalidAssociationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity and OriginalEntity must be of the same type..
        /// </summary>
        public static string InvalidChangeSet_MustBeSameType {
            get {
                return ResourceManager.GetString("InvalidChangeSet_MustBeSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity cannot be null..
        /// </summary>
        public static string InvalidChangeSet_NullEntity {
            get {
                return ResourceManager.GetString("InvalidChangeSet_NullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child entity of type &apos;{0}&apos; cannot be updated independent of its parent..
        /// </summary>
        public static string InvalidChangeset_UpdateChildWithoutParent {
            get {
                return ResourceManager.GetString("InvalidChangeset_UpdateChildWithoutParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex types cannot have association members..
        /// </summary>
        public static string InvalidComplexType_AssociationMember {
            get {
                return ResourceManager.GetString("InvalidComplexType_AssociationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex types cannot have composition members..
        /// </summary>
        public static string InvalidComplexType_CompositionMember {
            get {
                return ResourceManager.GetString("InvalidComplexType_CompositionMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainService &apos;{0}&apos; exposes both entity type &apos;{1}&apos; and complex type &apos;{2}&apos; which share an inheritance relationship. Entities cannot derive from complex types..
        /// </summary>
        public static string InvalidComplexType_EntityInheritance {
            get {
                return ResourceManager.GetString("InvalidComplexType_EntityInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex types cannot have include members..
        /// </summary>
        public static string InvalidComplexType_IncludeMember {
            get {
                return ResourceManager.GetString("InvalidComplexType_IncludeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainService &apos;{0}&apos; exposes both complex type &apos;{1}&apos; and complex type &apos;{2}&apos; which share an inheritance relationship. Only one complex type in an inheritance hierarchy can be exposed from a domain service..
        /// </summary>
        public static string InvalidComplexType_Inheritance {
            get {
                return ResourceManager.GetString("InvalidComplexType_Inheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex type &apos;{0}&apos; is invalid. Complex types cannot specify a KnownTypeAttribute..
        /// </summary>
        public static string InvalidComplexType_KnownTypes {
            get {
                return ResourceManager.GetString("InvalidComplexType_KnownTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; of complex type &apos;{1}&apos; is invalid. {2}.
        /// </summary>
        public static string InvalidComplexType_PropertyAttribute {
            get {
                return ResourceManager.GetString("InvalidComplexType_PropertyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom methods must contain at least one parameter..
        /// </summary>
        public static string InvalidCustomMethod_MethodCannotBeParameterless {
            get {
                return ResourceManager.GetString("InvalidCustomMethod_MethodCannotBeParameterless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; of domain method &apos;{1}&apos; must be an entity type exposed by the DomainService. The entity type can be exposed either directly in a query operation, or indirectly through an association..
        /// </summary>
        public static string InvalidDomainMethod_ParamMustBeEntity {
            get {
                return ResourceManager.GetString("InvalidDomainMethod_ParamMustBeEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid return type &apos;{0}&apos; for query method &apos;{1}&apos;. Query methods must have a return type that implements IEnumerable of T or must return a singleton..
        /// </summary>
        public static string InvalidDomainOperationEntry_InvalidQueryOperationReturnType {
            get {
                return ResourceManager.GetString("InvalidDomainOperationEntry_InvalidQueryOperationReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainOperationEntry &apos;{0}&apos; is not a Query operation so it cannot return a value..
        /// </summary>
        public static string InvalidDomainOperationEntry_NonQueryMustReturnVoid {
            get {
                return ResourceManager.GetString("InvalidDomainOperationEntry_NonQueryMustReturnVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{1}&apos; of domain operation entry &apos;{0}&apos; must be passed by value..
        /// </summary>
        public static string InvalidDomainOperationEntry_ParamMustBeByVal {
            get {
                return ResourceManager.GetString("InvalidDomainOperationEntry_ParamMustBeByVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{1}&apos; of domain operation entry &apos;{0}&apos; must be one of the predefined serializable types..
        /// </summary>
        public static string InvalidDomainOperationEntry_ParamMustBeSimple {
            get {
                return ResourceManager.GetString("InvalidDomainOperationEntry_ParamMustBeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid DomainOperation type for a DomainOperationEntry..
        /// </summary>
        public static string InvalidDomainOperationEntryType {
            get {
                return ResourceManager.GetString("InvalidDomainOperationEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid DomainOperation type for a ChangeSetEntry..
        /// </summary>
        public static string InvalidDomainOperationType {
            get {
                return ResourceManager.GetString("InvalidDomainOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid External specification for member &apos;{0}.{1}&apos;. ExternalReferenceAttribute can only be specified on members with the AssociationAttribute applied..
        /// </summary>
        public static string InvalidExternal_NonAssociationMember {
            get {
                return ResourceManager.GetString("InvalidExternal_NonAssociationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Include specification for member &apos;{0}.{1}&apos;. Non-projection includes can only be specified on members with the AssociationAttribute applied..
        /// </summary>
        public static string InvalidInclude_NonAssociationMember {
            get {
                return ResourceManager.GetString("InvalidInclude_NonAssociationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain operation entry &apos;{0}&apos; must take exactly one parameter..
        /// </summary>
        public static string InvalidInsertUpdateDeleteMethod_IncorrectParameterLength {
            get {
                return ResourceManager.GetString("InvalidInsertUpdateDeleteMethod_IncorrectParameterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation named &apos;{0}&apos; does not conform to the required signature. Parameter types must be an entity or complex type, a collection of entities or complex types, or one of the predefined serializable types..
        /// </summary>
        public static string InvalidInvokeOperation_ParameterType {
            get {
                return ResourceManager.GetString("InvalidInvokeOperation_ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation named &apos;{0}&apos; does not conform to the required signature. Return types must be an entity or complex type, a collection of entities or complex types, or one of the predefined serializable types..
        /// </summary>
        public static string InvalidInvokeOperation_ReturnType {
            get {
                return ResourceManager.GetString("InvalidInvokeOperation_ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member projection specification : MemberName cannot be empty..
        /// </summary>
        public static string InvalidMemberProjection_EmptyMemberName {
            get {
                return ResourceManager.GetString("InvalidMemberProjection_EmptyMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member projection specification : Path cannot be empty..
        /// </summary>
        public static string InvalidMemberProjection_EmptyPath {
            get {
                return ResourceManager.GetString("InvalidMemberProjection_EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member projection specification : The type of member &apos;{0}.{1}&apos; projected from member &apos;{2}.{3}&apos; is not one of the predefined serializable types..
        /// </summary>
        public static string InvalidMemberProjection_InvalidProjectedType {
            get {
                return ResourceManager.GetString("InvalidMemberProjection_InvalidProjectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member projection specification : Projection path &apos;{0}&apos; is invalid for member &apos;{1}.{2}&apos;. Please verify that the &apos;Path&apos; value specified in the IncludeAttribute on this member is correct. .
        /// </summary>
        public static string InvalidMemberProjection_Path {
            get {
                return ResourceManager.GetString("InvalidMemberProjection_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not derive from &apos;{1}&apos;..
        /// </summary>
        public static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The derived entity type &apos;{0}&apos; must be declared in a KnownTypeAttribute on the root entity &apos;{1}&apos;..
        /// </summary>
        public static string KnownTypeAttributeRequired {
            get {
                return ResourceManager.GetString("KnownTypeAttributeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; in the DomainService &apos;{1}&apos; is abstract and must use a KnownTypeAttribute to specify at least one non-abstract derived type..
        /// </summary>
        public static string KnownTypeAttributeRequired_Abstract {
            get {
                return ResourceManager.GetString("KnownTypeAttributeRequired_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}.{1}&apos; is not an compositional association member marked with CompositionAttribute..
        /// </summary>
        public static string MemberNotAComposition {
            get {
                return ResourceManager.GetString("MemberNotAComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}.{1}&apos; is not an association member marked with AssociationAttribute..
        /// </summary>
        public static string MemberNotAnAssociation {
            get {
                return ResourceManager.GetString("MemberNotAnAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; requires {1} parameters..
        /// </summary>
        public static string Method_Parameter_Count_Wrong {
            get {
                return ResourceManager.GetString("Method_Parameter_Count_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more roles must be specified..
        /// </summary>
        public static string RequiresRoleAttribute_MustSpecifyRole {
            get {
                return ResourceManager.GetString("RequiresRoleAttribute_MustSpecifyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous match for method &apos;{0}&apos;..
        /// </summary>
        public static string ValidationUtilities_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ValidationUtilities_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationContext.ObjectInstance cannot be null..
        /// </summary>
        public static string ValidationUtilities_ContextInstance_CannotBeNull {
            get {
                return ResourceManager.GetString("ValidationUtilities_ContextInstance_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}.{1}({3})&apos; could not be found. Parameter count: {2}..
        /// </summary>
        public static string ValidationUtilities_MethodNotFound {
            get {
                return ResourceManager.GetString("ValidationUtilities_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}.{1}&apos; accepting zero parameters could not be found..
        /// </summary>
        public static string ValidationUtilities_MethodNotFound_ZeroParams {
            get {
                return ResourceManager.GetString("ValidationUtilities_MethodNotFound_ZeroParams", resourceCulture);
            }
        }
    }
}
